import { db } from "../db/client.js";
import { dnsEvents } from "../db/schema.js";
import { eq } from "drizzle-orm";

// -----------------------------------------------------------------------
// Metric #85 — Query Type Distribution
// -----------------------------------------------------------------------
export function queryTypeDistribution(domain?: string) {
  const rows = domain
    ? db.select({ queryType: dnsEvents.queryType }).from(dnsEvents).where(eq(dnsEvents.domain, domain)).all()
    : db.select({ queryType: dnsEvents.queryType }).from(dnsEvents).all();

  const total = rows.length;
  const counts = new Map<string, number>();
  for (const r of rows) counts.set(r.queryType, (counts.get(r.queryType) ?? 0) + 1);

  return {
    totalQueries: total,
    breakdown: [...counts.entries()]
      .map(([queryType, count]) => ({ queryType, count, share: total > 0 ? count / total : 0 }))
      .sort((a, b) => b.count - a.count),
  };
}

// -----------------------------------------------------------------------
// Metric #86 — IPv4 vs IPv6 Resolution Mix
//   A vs AAAA query share network-wide, plus a per-client dual-stack vs.
//   IPv4-only classification (a client that only ever queries A records is
//   IPv4-only from what DNS can observe; one querying both is dual-stack).
// -----------------------------------------------------------------------
export function ipv4VsIpv6Mix() {
  const rows = db.select({ queryType: dnsEvents.queryType, clientId: dnsEvents.clientId }).from(dnsEvents).all();
  const aCount = rows.filter((r) => r.queryType === "A").length;
  const aaaaCount = rows.filter((r) => r.queryType === "AAAA").length;
  const total = aCount + aaaaCount;

  const byClient = new Map<string, { a: boolean; aaaa: boolean }>();
  for (const r of rows) {
    if (!r.clientId || (r.queryType !== "A" && r.queryType !== "AAAA")) continue;
    const bucket = byClient.get(r.clientId) ?? { a: false, aaaa: false };
    if (r.queryType === "A") bucket.a = true;
    if (r.queryType === "AAAA") bucket.aaaa = true;
    byClient.set(r.clientId, bucket);
  }

  const dualStackClients = [...byClient.values()].filter((c) => c.a && c.aaaa).length;
  const ipv4OnlyClients = [...byClient.values()].filter((c) => c.a && !c.aaaa).length;

  return {
    aQueries: aCount,
    aaaaQueries: aaaaCount,
    ipv4Share: total > 0 ? aCount / total : 0,
    ipv6Share: total > 0 ? aaaaCount / total : 0,
    dualStackClients,
    ipv4OnlyClients,
    totalClientsObserved: byClient.size,
  };
}

// -----------------------------------------------------------------------
// Metric #87 — CNAME Chain Depth
// KNOWN GAP: depends on dns_events.answer_data (the raw answer field),
// whose exact format from Technitium is UNCONFIRMED — needs live-instance
// verification, same discipline as the TTL/upstream fields were. Counts
// "CNAME" occurrences in the raw answer text as a heuristic depth proxy
// until that's confirmed.
// -----------------------------------------------------------------------
export function cnameChainDepth() {
  const rows = db.select({ answerData: dnsEvents.answerData }).from(dnsEvents).all();
  const withAnswer = rows.filter((r): r is { answerData: string } => !!r.answerData);

  if (withAnswer.length === 0) {
    return {
      hasData: false,
      note: "answer_data isn't populated by the collector yet, or its format hasn't been confirmed against a live Technitium instance — see the KNOWN GAP comment in protocol.ts.",
      distribution: null,
    };
  }

  const depths = withAnswer.map((r) => (r.answerData.match(/CNAME/gi) ?? []).length);
  return {
    hasData: true,
    note: "Heuristic: counts 'CNAME' occurrences in the raw answer text. UNCONFIRMED against a live instance — verify answer_data's real format before trusting these numbers.",
    avgDepth: depths.reduce((a, b) => a + b, 0) / depths.length,
    maxDepth: Math.max(...depths),
    sampleSize: depths.length,
  };
}

// -----------------------------------------------------------------------
// Metric #88 — Reverse DNS (PTR) Query Volume
//   PTR activity is often generated by security tools/logging rather than
//   normal browsing — worth tracking as its own signal.
// -----------------------------------------------------------------------
export function reverseDnsQueryVolume() {
  const rows = db.select({ queryType: dnsEvents.queryType, clientId: dnsEvents.clientId }).from(dnsEvents).all();
  const total = rows.length;
  const ptr = rows.filter((r) => r.queryType === "PTR");

  const byClient = new Map<string, number>();
  for (const r of ptr) {
    if (!r.clientId) continue;
    byClient.set(r.clientId, (byClient.get(r.clientId) ?? 0) + 1);
  }

  return {
    totalQueries: total,
    ptrQueries: ptr.length,
    share: total > 0 ? ptr.length / total : 0,
    topClients: [...byClient.entries()]
      .map(([clientId, count]) => ({ clientId, count }))
      .sort((a, b) => b.count - a.count)
      .slice(0, 10),
  };
}

// -----------------------------------------------------------------------
// Metric #89 — Malformed/Refused Query Rate
//   REFUSED share, distinct from NXDOMAIN (#14) — a misconfigured device
//   or active probing signal rather than "domain doesn't exist".
// KNOWN SCOPE LIMIT: genuinely unparseable/malformed queries that never
// make it into Technitium's query log at all are, by definition, invisible
// here — this only covers queries the server logged and rejected.
// -----------------------------------------------------------------------
export function malformedRefusedRate() {
  const rows = db.select({ responseCode: dnsEvents.responseCode, clientId: dnsEvents.clientId }).from(dnsEvents).all();
  const total = rows.length;
  const refused = rows.filter((r) => r.responseCode === "REFUSED");

  const byClient = new Map<string, number>();
  for (const r of refused) {
    if (!r.clientId) continue;
    byClient.set(r.clientId, (byClient.get(r.clientId) ?? 0) + 1);
  }

  return {
    totalQueries: total,
    refusedQueries: refused.length,
    rate: total > 0 ? refused.length / total : 0,
    topClients: [...byClient.entries()]
      .map(([clientId, count]) => ({ clientId, count }))
      .sort((a, b) => b.count - a.count)
      .slice(0, 10),
    note: "Only covers queries Technitium actually logged as REFUSED — truly unparseable queries that never reach the log aren't visible here.",
  };
}

// -----------------------------------------------------------------------
// Metric #90 — DoH/DoT/DoQ Bypass Attempts
//   Visible-at-the-DNS-layer attempts to resolve known public DoH/DoT/DoQ
//   provider hostnames — relevant to docs/NETWORK_LOCKDOWN.md's goal of
//   keeping all resolution flowing through the local resolver. Detects
//   only the DNS lookup for the provider's hostname itself, not the
//   encrypted DoH/DoT/DoQ traffic that would follow it (which is
//   invisible to a DNS-layer collector by design).
// -----------------------------------------------------------------------
const KNOWN_DOH_DOT_DOQ_HOSTNAMES = [
  "cloudflare-dns.com",
  "dns.google",
  "dns.quad9.net",
  "doh.opendns.com",
  "dns.adguard.com",
  "doh.cleanbrowsing.org",
  "dns.nextdns.io",
  "family.cloudflare-dns.com",
  "security.cloudflare-dns.com",
  "doh.mullvad.net",
];

export function dohDotDoqBypassAttempts() {
  const rows = db.select({ domain: dnsEvents.domain, clientId: dnsEvents.clientId, timestamp: dnsEvents.timestamp }).from(dnsEvents).all();
  const hits = rows.filter((r) => KNOWN_DOH_DOT_DOQ_HOSTNAMES.some((h) => r.domain === h || r.domain.endsWith(`.${h}`)));

  const byClient = new Map<string, number>();
  for (const h of hits) {
    if (!h.clientId) continue;
    byClient.set(h.clientId, (byClient.get(h.clientId) ?? 0) + 1);
  }

  return {
    totalAttempts: hits.length,
    byClient: [...byClient.entries()].map(([clientId, count]) => ({ clientId, count })).sort((a, b) => b.count - a.count),
    recentAttempts: hits.slice(-20).reverse(),
    note: "Detects the DNS lookup for a known DoH/DoT/DoQ provider hostname only — the encrypted traffic that would follow is invisible at the DNS layer by design.",
  };
}
